### ISSUE TITLE
Compare with deep learning model

### ISSUE THREAD

**Issue by ghost** [VaclavDedik/triager#23]
Hi @VaclavDedik , thanks for the great work! Sorry to post the question here: are you planning to test any Deep Learning model and compare with your existent result?

Cheers!

**Comment by VaclavDedik** [comment]
Hi @fracting ! No problem! I am not planning that, all tested models are in [my master thesis](https://is.muni.cz/th/374278/fi_m/thesis.pdf). It's not likely I'll test any other models in the near future.

**Comment by ghost** [comment]
Thanks for quick response! I was reading your master thesis first and then follow to the link of your github project, sorry for didn't state clearly.

Anyway it's very nice research, thank you! Question answered, I'm closing the issue.
